import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Banknote,
  Bell,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CheckCircle2,
  Clock,
  Copy,
  CreditCard,
  Eye,
  ExternalLink,
  Hand,
  Heart,
  LayoutDashboard,
  Lock,
  LogOut,
  MapPin,
  Menu,
  MessageCircle,
  PenTool,
  Phone,
  Plus,
  Search,
  Scissors,
  Sparkles,
  Star,
  TrendingUp,
  User,
  Users,
  Wallet,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";
import type { ServiceCategory } from "@/data/services";

export type { LucideIcon };

export const categoryIcons: Record<ServiceCategory, LucideIcon> = {
  facial: Sparkles,
  corporal: Heart,
  micropigmentacao: PenTool,
  unhas: Hand,
  cilios: Eye,
  depilacao: Scissors,
};

export const dashNavIcons: Record<string, LucideIcon> = {
  "/dashboard": LayoutDashboard,
  "/dashboard/agenda": CalendarDays,
  "/dashboard/agendamentos": CalendarDays,
  "/dashboard/financeiro": Wallet,
  "/dashboard/profissionais": Users,
};

export const statusIcons: Record<string, LucideIcon> = {
  pending: CalendarClock,
  scheduled: CalendarClock,
  confirmed: CalendarCheck,
  in_progress: Clock,
  completed: CheckCircle2,
  finished: CheckCircle2,
  cancelled: XCircle,
  no_show: AlertCircle,
  rescheduled: CalendarDays,
  paid: CheckCircle2,
  refunded: AlertCircle,
};

export {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Banknote,
  Bell,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CheckCircle2,
  Clock,
  Copy,
  CreditCard,
  Eye,
  ExternalLink,
  Hand,
  Heart,
  LayoutDashboard,
  Lock,
  LogOut,
  MapPin,
  Menu,
  MessageCircle,
  PenTool,
  Phone,
  Plus,
  Search,
  Scissors,
  Sparkles,
  Star,
  TrendingUp,
  User,
  Users,
  Wallet,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
};
